a.out: main.cpp reading.cpp Shape.cpp Sphere.cpp Cylinder.cpp Box.cpp Torus.cpp
	g++ -std=c++11 main.cpp reading.cpp Shape.cpp Sphere.cpp Cylinder.cpp Box.cpp Torus.cpp -Wall

.PHONY: clean clean_win

clean:
	rm -f a.out