(define PI 3.1415926535897932384626433832795028841971693993751)

(define (get_area line)
  (let ((type (list-ref line 1)) (area 0))
    (cond
      ((string=? type "box")
        (let ((length (list-ref line 2)))
          (let ((width (list-ref line 3)))
            (let ((height (list-ref line 4)))
              (set! height (remove_carriage height))
              (set! length (string->number length))
              (set! width (string->number width))
              (set! height (string->number height))
              (set! area (+ (* 2 length width) (* 2 length height) (* 2 width height)))))))
      ((string=? type "cylinder")
        (let ((radius (list-ref line 2)))
          (let ((height (list-ref line 3)))
            (set! height (remove_carriage height))
            (set! radius (string->number radius))
            (set! height (string->number height))
            (set! area (+ (* 2 PI radius height) (* 2 PI (* radius radius)))))))
      ((string=? type "sphere")
        (let ((radius (list-ref line 2)))
          (set! radius (remove_carriage radius))
          (set! radius (string->number radius))
          (set! area (* 4 PI (* radius radius)))))
      ((string=? type "torus")
        (let ((small_radius (list-ref line 2)))
          (let ((big_radius (list-ref line 3)))
            (set! big_radius (remove_carriage big_radius))
            (set! small_radius (string->number small_radius))
            (set! big_radius (string->number big_radius))
            (set! area (* 4 (* PI PI) small_radius big_radius)))))
      (else
        (begin
          (display "Unknown shape type.\n"))))
    (set! area (number->string area))
    area))

(define (get_volume line)
  (let ((type (list-ref line 2)) (volume 0))
    (cond
      ((string=? type "box")
        (let ((length (list-ref line 3)))
          (let ((width (list-ref line 4)))
            (let ((height (list-ref line 5)))
              (set! height (remove_carriage height))
              (set! length (string->number length))
              (set! width (string->number width))
              (set! height (string->number height))
              (set! volume (* length width height))))))
      ((string=? type "cylinder")
        (let ((radius (list-ref line 3)))
          (let ((height (list-ref line 4)))
            (set! height (remove_carriage height))
            (set! radius (string->number radius))
            (set! height (string->number height))
            (set! volume (* PI (* radius radius) height)))))
      ((string=? type "sphere")
        (let ((radius (list-ref line 3)))
          (set! radius (remove_carriage radius))
          (set! radius (string->number radius))
          (set! volume (* (/ 4 3) PI (* radius radius radius)))))
      ((string=? type "torus")
        (let ((small_radius (list-ref line 3)))
          (let ((big_radius (list-ref line 4)))
            (set! big_radius (remove_carriage big_radius))
            (set! small_radius (string->number small_radius))
            (set! big_radius (string->number big_radius))
            (set! volume (* (* PI (* small_radius small_radius) (* big_radius 2)) (* PI))))))
      (else
        (begin
          (display "Unknown shape type.\n"))))
    (set! volume (number->string volume))
    volume))

(define (get_info line)
  (let ((type (list-ref line 3)) (info ""))
    (cond
      ((string=? type "box")
        (set! info (build_str "Box: " (list-ref line 2) ", Length=" (list-ref line 4) ", Width=" (list-ref line 5) ", Height=" (remove_carriage (list-ref line 6)) "\n\tSurface Area: " (list-ref line 1) ", Volume: " (list-ref line 0))))
      ((string=? type "cylinder")
        (set! info (build_str "Cylinder: " (list-ref line 2) ", Radius=" (list-ref line 4) ", Height=" (remove_carriage (list-ref line 5)) "\n\tSurface Area: " (list-ref line 1) ", Volume: " (list-ref line 0))))
      ((string=? type "sphere")
        (set! info (build_str "Sphere: " (list-ref line 2) ", Radius=" (remove_carriage (list-ref line 4)) "\n\tSurface Area: " (list-ref line 1) ", Volume: " (list-ref line 0))))
      ((string=? type "torus")
        (set! info (build_str "Torus: " (list-ref line 2) ", Small Radius=" (list-ref line 4) ", Big Radius=" (remove_carriage (list-ref line 5)) "\n\tSurface Area: " (list-ref line 1) ", Volume: " (list-ref line 0)))))
    info))

(define (build_str . args)
  (define (concat lst)
    (if (null? lst)
        ""
        (string-append (car lst) (concat (cdr lst)))))
  (concat args))


(define (split_conditions x)
  (define (collect i word line)
    (cond
      ((>= i (string-length x))
        (if (null? word)
          line
          (append line (list (list->string (reverse word))))))
      ((char=? (string-ref x i) #\space)
        (collect (+ i 1) '()
          (if (null? word)
            line
            (append line (list (list->string (reverse word)))))))
      (else
        (collect (+ i 1)
          (cons (string-ref x i) word)
          line))))
  (collect 0 '() '()))


(define (test lines type op value)
  (let ((newShapes '()))
    (cond
      ((string=? type "type")
        (cond
          ((string=? op "==")
            (for-each (lambda (line)
                (if (string=? (list-ref line 4) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op "!=")
            (for-each (lambda (line)
                (if (not (string=? (list-ref line 4) value))
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op ">")
            (for-each (lambda (line)
                (if (string>? (list-ref line 4) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op "<")
            (for-each (lambda (line)
                (if (string<? (list-ref line 4) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op "<=")
            (for-each (lambda (line)
                (if (string<=? (list-ref line 4) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op ">=")
            (for-each (lambda (line)
                (if (string>=? (list-ref line 4) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))))
      ((string=? type "area")
        (cond
          ((string=? op "==")
            (for-each (lambda (line)
                (if (= (string->number (list-ref line 2)) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op "!=")
            (for-each (lambda (line)
                (if (not (= (string->number (list-ref line 2)) value))
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op ">")
            (for-each (lambda (line)
                (if (> (string->number (list-ref line 2)) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op "<")
            (for-each (lambda (line)
                (if (< (string->number (list-ref line 2)) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op "<=")
            (for-each (lambda (line)
                (if (<= (string->number (list-ref line 2)) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op ">=")
            (for-each (lambda (line)
                (if (>= (string->number (list-ref line 2)) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))))
      ((string=? type "volume")
        (cond
          ((string=? op "==")
            (for-each (lambda (line)
                (if (= (string->number (list-ref line 1)) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op "!=")
            (for-each (lambda (line)
                (if (not (= (string->number (list-ref line 1)) value))
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op ">")
            (for-each (lambda (line)
                (if (> (string->number (list-ref line 1)) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op "<")
            (for-each (lambda (line)
                (if (< (string->number (list-ref line 1)) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op "<=")
            (for-each (lambda (line)
                (if (<= (string->number (list-ref line 1)) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes))
          ((string=? op ">=")
            (for-each (lambda (line)
                (if (>= (string->number (list-ref line 1)) value)
                  (set! newShapes (cons line newShapes)))) lines)
            (set! lines newShapes)))))
    lines))

(define (print_shapes lines action)
  (cond
    ((string=? action "print")
      (newline)
      (for-each (lambda (line)
          (display (car line))
          (newline))
        (reverse lines)))
    ((string=? action "count")
      (display (string-append "\nThere are " (number->string (length lines)) " shapes.\n")))
    ((or (string=? action "total") (string=? action "avg"))
      (let ((totalArea 0) (totalVolume 0))
        (for-each (lambda (line)
            (let ((area (string->number (list-ref line 2)))
                (volume (string->number (list-ref line 1))))
              (set! totalArea (+ totalArea area))
              (set! totalVolume (+ totalVolume volume))))
          lines)
        (if (string=? action "total")
          (display (string-append "\ntotal(Surface Area)=" (number->string totalArea) "\ntotal(Volume)=" (number->string totalVolume) "\n")))
        (if (string=? action "avg")
          (let ((avgArea 0) (avgVolume 0))
            (set! avgArea (/ totalArea (length lines)))
            (set! avgVolume (/ totalVolume (length lines)))
            (display (string-append "\navg(Surface Area)=" (number->string avgArea) "\navg(Volume)=" (number->string avgVolume) "\n"))))))
    ((string=? action "min")
      (let ((minArea (string->number (list-ref (list-ref lines 0) 2))) (minVolume (string->number (list-ref (list-ref lines 0) 1))))
        (for-each (lambda (line)
            (if (< (string->number (list-ref line 2)) minArea)
              (set! minArea (string->number (list-ref line 2))))
            (if (< (string->number (list-ref line 1)) minVolume)
              (set! minVolume (string->number (list-ref line 1)))))
          lines)
        (display (string-append "\nmin(Surface Area)=" (number->string minArea) "\nmin(Volume)=" (number->string minVolume) "\n"))))
    ((string=? action "max")
      (let ((maxArea (string->number (list-ref (list-ref lines 0) 2))) (maxVolume (string->number (list-ref (list-ref lines 0) 1))))
        (for-each (lambda (line)
            (if (> (string->number (list-ref line 2)) maxArea)
              (set! maxArea (string->number (list-ref line 2))))
            (if (> (string->number (list-ref line 1)) maxVolume)
              (set! maxVolume (string->number (list-ref line 1)))))
          lines)
        (display (string-append "\nmax(Surface Area)=" (number->string maxArea) "\nmax(Volume)=" (number->string maxVolume) "\n"))))))

(define (iter_matrix action lines args)
  (define (process-arg arg lines)
    (define (inner j lines)
      (if (>= j (length arg))
        lines
        (let* ((type (list-ref arg j))
            (op (list-ref arg (+ j 1)))
            (value (list-ref arg (+ j 2)))
            (new-lines (test lines type op value)))
          (inner (+ j 3) new-lines))))
    (inner 0 lines))
  (define (outer i lines)
    (if (>= i (length args))
      (print_shapes lines action)
      (outer (+ i 1) (process-arg (list-ref args i) lines))))
  (outer 0 lines))


(define (display_shapes action lines . condtions_args)
  (if (not (null? condtions_args))
    (iter_matrix action lines condtions_args)
    (print_shapes lines action)))

(define (perform action fileName . condtions_args)
  (if (not (file-exists? fileName))
    (begin
      (display (string-append "\nUnable to open " fileName " for reading.\n\n"))
      #f)
    (begin
      (let ((lines '()))
        (let ((input-port (open-input-file fileName)))
          (let loop ((line (read-line input-port)))
            (cond ((eof-object? line)
                (close-input-port input-port))
              (else
                (set! line (split_conditions line))
                (let ((area (get_area line)))
                  (set! line (cons area line)))
                (let ((volume (get_volume line)))
                  (set! line (cons volume line)))
                (let ((info (get_info line)))
                  (set! line (cons info line)))
                (set! lines (cons line lines))
                (loop (read-line input-port))))))
        (if (null? condtions_args)
          (begin
            (print_shapes lines action))
          (begin
            (if (not (zero? (modulo (length condtions_args) 3)))
              (begin
                (display "Incorrect number of arguments.\n")
                #f)
              (begin
                (display_shapes action lines condtions_args)))))))))

(define (remove_carriage str)
  (let ((len (string-length str)))
    (if (and (> len 0) (char=? (string-ref str (- len 1)) #\return))
        (substring str 0 (- len 1))
        str)))
