(define PI 3.1415926535897932384626433832795028841971693993751)

(define (remove_carriage str)
  (if (string-suffix? "\r" str)
    (substring str 0 (- (string-length str) 1))
    str))

(define (split_conditions x)
  (let ((line '())
      (word '()))
    (let loop ((i 0))
      (cond ((>= i (string-length x))
          (if (not (null? word))
            (set! line (append line (list (list->string (reverse word))))))
          line)
        ((char=? (string-ref x i) #\space)
          (if (not (null? word))
            (set! line (append line (list (list->string (reverse word))))))
          (set! word '())
          (loop (+ i 1)))
        (else
          (set! word (cons (string-ref x i) word))
          (loop (+ i 1)))))))

(define (get_area line)
  (let ((type (list-ref line 1))
      (area 0))
    (cond
      ((string=? type "box")
        (let ((length (list-ref line 2)))
          (let ((width (list-ref line 3)))
            (let ((height (list-ref line 4)))
              (set! height (remove_carriage height))
              (set! length (string->number length))
              (set! width (string->number width))
              (set! height (string->number height))
              (set! area (+ (* 2 length width) (* 2 length height) (* 2 width height)))))))
      ((string=? type "torus")
        (let ((smail_radius (list-ref line 2)))
          (let ((big_radius (list-ref line 3)))
            (set! big_radius (remove_carriage big_radius))
            (set! smail_radius (string->number smail_radius))
            (set! big_radius (string->number big_radius))
            (set! area (* (* PI (* smail_radius smail_radius) (* big_radius 2)) (* PI))))))
      ((string=? type "cylinder")
        (let ((radius (list-ref line 2)))
          (let ((height (list-ref line 3)))
            (set! height (remove_carriage height))
            (set! radius (string->number radius))
            (set! height (string->number height))
            (set! area (+ (* 2 PI radius height) (* 2 PI (* radius radius)))))))
      ((string=? type "sphere")
        (let ((radius (list-ref line 2)))
          (set! radius (remove_carriage radius))
          (set! radius (string->number radius))
          (set! area (* 4 PI (* radius radius)))))
      (else
        (begin
          (display "Unknown shape type.")
          (newline))))
    (set! area (number->string area))
    area))

(define (get_volume line)
  (let ((type (list-ref line 2))
      (volume 0))
    (cond
      ((string=? type "box")
        (let ((length (list-ref line 3)))
          (let ((width (list-ref line 4)))
            (let ((height (list-ref line 5)))
              (set! height (remove_carriage height))
              (set! length (string->number length))
              (set! width (string->number width))
              (set! height (string->number height))
              (set! volume (* length width height))))))
      ((string=? type "torus")
        (let ((smail_radius (list-ref line 3)))
          (let ((big_radius (list-ref line 4)))
            (set! big_radius (remove_carriage big_radius))
            (set! smail_radius (string->number smail_radius))
            (set! big_radius (string->number big_radius))
            (set! volume (* (* PI (* smail_radius smail_radius) (* big_radius 2)) (* PI))))))
      ((string=? type "cylinder")
        (let ((radius (list-ref line 3)))
          (let ((height (list-ref line 4)))
            (set! height (remove_carriage height))
            (set! radius (string->number radius))
            (set! height (string->number height))
            (set! volume (* PI (* radius radius) height)))))
      ((string=? type "sphere")
        (let ((radius (list-ref line 3)))
          (set! radius (remove_carriage radius))
          (set! radius (string->number radius))
          (set! volume (* 4 PI (* radius radius radius) (/ 3.0)))))
      (else
        (begin
          (display "Unknown shape type.")
          (newline))))
    (set! volume (number->string volume))
    volume))

(define (check_len args)
  (if (zero? (modulo (length args) 3))
    #t
    #f))

(define (get_info line)
  (let ((type (list-ref line 3))
      (info ""))
    (cond
      ((string=? type "box")
        (set! info (build_str "Box: " (list-ref line 2) ", Length=" (list-ref line 4) ", Width=" (list-ref line 5) ", Height=" (remove_carriage (list-ref line 6)) "\n\tSurface Area: " (list-ref line 1) ", Volume: " (list-ref line 0))))
      ((string=? type "torus")
        (set! info (build_str "Torus: " (list-ref line 2) ", Small Radius=" (list-ref line 4) ", Big Radius=" (remove_carriage (list-ref line 5)) "\n\tSurface Area: " (list-ref line 1) ", Volume: " (list-ref line 0))))
      ((string=? type "cylinder")
        (set! info (build_str "Cylinder: " (list-ref line 2) ", Radius=" (list-ref line 4) ", Height=" (remove_carriage (list-ref line 5)) "\n\tSurface Area: " (list-ref line 1) ", Volume: " (list-ref line 0))))
      ((string=? type "sphere")
        (set! info (build_str "Sphere: " (list-ref line 2) ", Radius=" (remove_carriage (list-ref line 4)) "\n\tSurface Area: " (list-ref line 1) ", Volume: " (list-ref line 0)))))
    info))

(define (build_str . args)
  (apply string-append args))

(define (process_conditions lines type op value)
  (let ((newLines '()))
    (cond
      ((string=? type "type")
        (cond
          ((string=? op "==")
            (for-each (lambda (line)
                (if (string=? (list-ref line 4) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op "!=")
            (for-each (lambda (line)
                (if (not (string=? (list-ref line 4) value))
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op ">")
            (for-each (lambda (line)
                (if (string>? (list-ref line 4) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op "<")
            (for-each (lambda (line)
                (if (string<? (list-ref line 4) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op "<=")
            (for-each (lambda (line)
                (if (string<=? (list-ref line 4) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op ">=")
            (for-each (lambda (line)
                (if (string>=? (list-ref line 4) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))))
      ((string=? type "area")
        (cond
          ((string=? op "==")
            (for-each (lambda (line)
                (if (= (string->number (list-ref line 2)) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op "!=")
            (for-each (lambda (line)
                (if (not (= (string->number (list-ref line 2)) value))
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op ">")
            (for-each (lambda (line)
                (if (> (string->number (list-ref line 2)) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op "<")
            (for-each (lambda (line)
                (if (< (string->number (list-ref line 2)) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op "<=")
            (for-each (lambda (line)
                (if (<= (string->number (list-ref line 2)) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op ">=")
            (for-each (lambda (line)
                (if (>= (string->number (list-ref line 2)) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))))
      ((string=? type "volume")
        (cond
          ((string=? op "==")
            (for-each (lambda (line)
                (if (= (string->number (list-ref line 1)) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op "!=")
            (for-each (lambda (line)
                (if (not (= (string->number (list-ref line 1)) value))
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op ">")
            (for-each (lambda (line)
                (if (> (string->number (list-ref line 1)) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op "<")
            (for-each (lambda (line)
                (if (< (string->number (list-ref line 1)) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op "<=")
            (for-each (lambda (line)
                (if (<= (string->number (list-ref line 1)) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines))
          ((string=? op ">=")
            (for-each (lambda (line)
                (if (>= (string->number (list-ref line 1)) value)
                  (set! newLines (cons line newLines)))) lines)
            (set! lines newLines)))))
    lines))

(define (print_shapes lines action)
  (cond
    ((string=? action "print")
      (newline)
      (for-each (lambda (line)
          (display (car line))
          (newline))
        (reverse lines)))
    ((string=? action "count")
      (display (string-append "\nThere are " (number->string (length lines)) " shapes.\n")))
    ((string=? action "total")
      (let ((totalArea 0) (totalVolume 0))
        (for-each (lambda (line)
            (let ((area (string->number (list-ref line 2)))
                (volume (string->number (list-ref line 1))))
              (set! totalArea (+ totalArea area))
              (set! totalVolume (+ totalVolume volume))))
          lines)
        (display (string-append "\ntotal (Surface Area) = " (number->string totalArea) "\ntotal (Volume) = " (number->string totalVolume) "\n"))))
    ((string=? action "min")
      (let ((minArea (string->number (list-ref (list-ref lines 0) 2))) (minVolume (string->number (list-ref (list-ref lines 0) 1))))
        (for-each (lambda (line)
            (if (< (string->number (list-ref line 2)) minArea)
              (set! minArea (string->number (list-ref line 2))))
            (if (< (string->number (list-ref line 1)) minVolume)
              (set! minVolume (string->number (list-ref line 1)))))
          lines)
        (display (string-append "\nmin (Surface Area) = " (number->string minArea) "\nmin (Volume) = " (number->string minVolume) "\n"))))
    ((string=? action "max")
      (let ((maxArea (string->number (list-ref (list-ref lines 0) 2))) (maxVolume (string->number (list-ref (list-ref lines 0) 1))))
        (for-each (lambda (line)
            (if (> (string->number (list-ref line 2)) maxArea)
              (set! maxArea (string->number (list-ref line 2))))
            (if (> (string->number (list-ref line 1)) maxVolume)
              (set! maxVolume (string->number (list-ref line 1)))))
          lines)
        (display (string-append "\nmax (Surface Area) = " (number->string maxArea) "\nmax (Volume) = " (number->string maxVolume) "\n"))))
    ((string=? action "avg")
      (let ((totalArea 0) (totalVolume 0))
        (for-each (lambda (line)
            (let ((area (string->number (list-ref line 2))) (volume (string->number (list-ref line 1))))
              (set! totalArea (+ totalArea area))
              (set! totalVolume (+ totalVolume volume))))
          lines)
        (let ((avgArea 0) (avgVolume 0) (l (length lines)))
          (set! avgArea (/ totalArea l))
          (set! avgVolume (/ totalVolume l))
          (display (string-append "\navg (Surface Area) = " (number->string avgArea) "\navg (Volume) = " (number->string avgVolume) "\n")))))))

(define (iter_matrix action lines args)
  (do ((i 0 (+ i 1)))
    ((>= i (length args)))
    (do ((j 0 (+ j 3)))
      ((>= j (length (car args))))
      (let ((type (list-ref (list-ref args i) j))
          (op (list-ref (list-ref args i) (+ j 1)))
          (value (list-ref (list-ref args i) (+ j 2))))
        (set! lines (process_conditions lines type op value)))))
  (print_shapes lines action))

(define (display_shapes action lines . condtions_args)
  (if (not (null? condtions_args))
    (iter_matrix action lines condtions_args)
    (print_shapes lines action)))

(define (perform action fileName . condtions_args)
  (if (not (file-exists? fileName))
    (begin
      (display (string-append "\nUnable to open " fileName " for reading.\n\n"))
      #f)
    (begin
      (let ((lines '()))
        (let ((input-port (open-input-file fileName)))
          (let loop ((line (read-line input-port)))
            (cond ((eof-object? line)
                (close-input-port input-port))
              (else
                (set! line (split_conditions line))
                (let ((area (get_area line)))
                  (set! line (cons area line)))
                (let ((volume (get_volume line)))
                  (set! line (cons volume line)))
                (let ((info (get_info line)))
                  (set! line (cons info line)))
                (set! lines (cons line lines))
                (loop (read-line input-port))))))
        (if (null? condtions_args)
          (begin
            (print_shapes lines action))
          (begin
            (if (not (check_len condtions_args))
              (begin
                (display "Incorrect number of arguments.")
                (newline)
                #f)
              (begin
                (display_shapes action lines condtions_args)))))))))
